steps:
  - name: 'bash'
    script: |
      echo "GCP Cloud Build - Sec1 Security"
      echo "Your project ID is $PROJECT_ID"
      echo "Your project ID is $REPO_NAME : $REPO_FULL_NAME"
      echo "Repository URL: $_REPO_URL"
substitutions:
  _REPO_URL: '${REPO_FULL_NAME}'
options:
    dynamicSubstitutions: true
