steps:
  - id: 'get-api-key'
  uses: 'google-github-actions/get-secretmanager-secrets@v0'
  with:
    secrets: |-
      token:my-project/mysql-password-secret

# Example of using the output
 - id: 'bash'
   entrypoint: '/bin/sh'
   args:
   - '-c'
   - |
     echo "GCP Cloud Build - Sec1 Security ${REPO_FULL_NAME}"
     echo "${{ steps.get-api-key.outputs.SEC1_API_KEY }}"
   env:
     SEC1_API_KEY: '${{ steps.get-api-key.outputs.SEC1_API_KEY }}'
