steps:
  - name: 'bash'
    entrypoint: '/bin/sh'
    args:
    - '-c'
    - |
      echo "GCP Cloud Build - Sec1 Security ${REPO_FULL_NAME}"
      echo "${_SECRETS.SEC1_API_KEY}"
    secretEnv: ['SEC1_API_KEY']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SEC1_API_KEY/versions/latest
    env: 'SEC1_API_KEY'
