steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args:
    - 'run'
    - '--rm'
    - '-v'
    - '/tmp/resilient-foss-cli:/app/scan-directory'
    - '-e'
    - 'SEC1_INTEGRATION_NAME=GCP'
    - '-e'
    - 'INPUT_APIKEY=$$SEC1_API_KEY'
    - 'rsdsec1/test:sec1-foss-security-v3'
      ##echo $$SEC1_API_KEY
      #docker run -e SCAN_DIRECTORY=/workspace -v rsdsec1/test:sec1-foss-security -e INPUT_APIKEY=$$SEC1_API_KEY -e GCP=true sec1-cli
    secretEnv: ['SEC1_API_KEY']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SEC1_API_KEY/versions/latest
    env: 'SEC1_API_KEY'
