steps:
  - name: 'bash'
    entrypoint: '/bin/sh'
    args:
    - '-c'
    - |
      echo "GCP Cloud Build - Sec1 Security ${REPO_FULL_NAME}"
      echo "Secret before: $${_SECRETS.SEC1_API_KEY}"
      export SECRET_VALUE="$${_SECRETS.SEC1_API_KEY}"
      echo "Secret after: $SECRET_VALUE"
    secretEnv: ['SEC1_API_KEY']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SEC1_API_KEY/versions/latest
    env: 'SEC1_API_KEY'
substitutions:
  _SECRETS.SEC1_API_KEY: "$${_SECRETS.SEC1_API_KEY}"
