steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/sh'
    args:
    - '-c'
    - |
      echo "GCP Cloud Build - Sec1 Security"
      _REPO_URL=$(git config --get remote.origin.url)
      echo "Repository URL: $_REPO_URL"
substitutions:
  _REPO_URL: ''
options:
    dynamicSubstitutions: true
